# Generated by Django 5.0.6 on 2025-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pwd_remove_rental_posted_by_delete_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwd',
            name='gender',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
