# Generated by Django 5.0.6 on 2025-06-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_infrastructure_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorCitizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('location', models.TextField()),
            ],
        ),
    ]
