# Generated by Django 5.0.6 on 2025-06-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_households_householdmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='role',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
