# Generated by Django 5.0.6 on 2024-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rental_vehicle_type_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
