# Generated by Django 5.0.6 on 2025-06-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_householdmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='households',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='role',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter')], max_length=20),
        ),
    ]
