# Generated by Django 5.0.6 on 2024-08-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_schedule_enddate_remove_schedule_startdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(null=True, blank=True),  # Correct type for time values
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(null=True, blank=True),  # Correct type for time values
        ),
    ]
