# Generated by Django 5.0.6 on 2025-06-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-20T11:38:00'),
            preserve_default=False,
        ),
    ]
