# Generated by Django 5.0.6 on 2024-08-13 02:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_qrcode_pension_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='qr',
            field=models.FileField(blank=True, upload_to='qrs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='endDatetime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startDatetime',
            field=models.TimeField(),
        ),
        migrations.DeleteModel(
            name='QrCode',
        ),
    ]
