# Generated by Django 5.0.6 on 2024-10-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_pension_notification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='1990-05-15'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pension',
            name='status',
            field=models.TextField(default='Not Eligible'),
        ),
    ]
