# Generated by Django 5.0.6 on 2024-10-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile_dob_alter_pension_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
