# Generated by Django 5.0.6 on 2024-10-05 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='requirement1',
            field=models.FileField(default=1, upload_to='ids/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pension',
            name='requirement2',
            field=models.FileField(default=1, upload_to='authorization-letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
            preserve_default=False,
        ),
    ]
