# Generated by Django 5.0.6 on 2024-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_pension_requirement1_pension_requirement2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField()),
            ],
        ),
    ]
